import abc
from typing import List

class AIEngine(abc.ABC):
    @abc.abstractmethod
    @abc.abstractmethod
    async def generate(self, instruction: str, image_url: str = None) -> str | None:
        pass

class MockEngine(AIEngine):
    async def generate(self, instruction: str, image_url: str = None) -> str | None:
        # Mock doesn't really generate images, just placeholder
        return None

import os
import json
from openai import AsyncOpenAI
from dotenv import load_dotenv

load_dotenv()

class APIEngine(AIEngine):
    def __init__(self):
        self.client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    async def generate(self, instruction: str, image_url: str = None) -> str | None:
        # APIEngine (OpenAI) currently doesn't support image generation in this flow easily without DALL-E.
        # Returning None for now.
        return None



try:
    from google import genai
    from google.genai import types
    from PIL import Image
    import io
    import numpy as np
except ImportError:
    pass # Handle missing deps gracefully if running without them

class GeminiEngine(AIEngine):
    def __init__(self):
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            print("Warning: GEMINI_API_KEY not found.")
        self.client = genai.Client(api_key=api_key)

    async def generate(self, instruction: str, image_url: str = None) -> str | None:
        
        prompt = instruction
        
        input_image = None
        if image_url:
             try:
                import httpx
                async with httpx.AsyncClient() as client:
                    resp = await client.get(image_url)
                    if resp.status_code == 200:
                        image_bytes = resp.content
                        input_image = Image.open(io.BytesIO(image_bytes))
             except Exception as e:
                 print(f"Failed to download image: {e}")

        try:
            # Use Gemini 2.5 Flash Image (Nano Banana) for Multimodal generation
            # Allows Text + Image input -> Image output
            
            contents = [prompt]
            if input_image:
                contents.append(input_image)

            # Note: For generating images with Gemini, we use generate_content 
            # and expect image output if supported.
            # We might need to specify config to output image.
            
            response = self.client.models.generate_content(
                model='gemini-2.5-flash-image',
                contents=contents,
                config=types.GenerateContentConfig(
                    response_modalities=['IMAGE'],
                    # safety_settings=...
                )
            )
            
            # Extract image from response
            image_bytes = None
            for part in response.parts:
                # Check for inline data (image)
                if part.inline_data:
                    image_bytes = part.inline_data.data
                    break
                # Or executable code that produced image? 
                # Usually native image gen returns inline_data with mime_type image/jpeg or png
                
            if not image_bytes:
                # Fallback: Check if it generated images via the 'generated_images' attribute 
                # (if SDK maps it differently for this model)
                if hasattr(response, 'generated_images') and response.generated_images:
                     image_bytes = response.generated_images[0].image.image_bytes

            if not image_bytes:
                print("No image generated by Gemini 2.5")
                return None

            # Convert to Base64 for frontend
            import base64
            base64_image = "data:image/jpeg;base64," + base64.b64encode(image_bytes).decode('utf-8')
            
            return base64_image

        except Exception as e:
            print(f"Gemini API Error: {e}")
            return None


class LocalEngine(AIEngine):
    async def generate(self, instruction: str, image_url: str = None) -> str | None:
        # TODO: Implement Local Model call
        return None

def get_engine(model_type: str) -> AIEngine:
    if model_type == "gemini":
        return GeminiEngine()
    # Always use APIEngine for Vercel deployment as per user request
    return APIEngine()

